image: fedora:39

linux:
  stage: build
  script:
    - dnf install -y git gcc-c++ fontconfig-devel freetype-devel libvorbis-devel libepoxy-devel libwebp-devel boost-python3-devel python3-devel cmake ninja-build SDL2-devel libatomic
    - cmake -Bbuild -GNinja
    - ninja -C build

server:
  image: ubuntu:20.04
  stage: build
  script:
    - apt-get update && apt-get install -y cmake ninja-build libsoci-dev libsqlite3-dev g++ git libboost-system-dev libboost-coroutine-dev
    - cd server
    - cmake -Bbuild -GNinja
    - cmake --build build

web:
  image: emscripten/emsdk:3.1.61
  stage: build
  script:
    - apt-get update && apt-get install -y ninja-build
    - cd /tmp
    - curl --silent -O -L https://archives.boost.io/release/1.82.0/source/boost_1_82_0.tar.bz2
    - tar --wildcards -xf *.tar.bz2 'boost_1_*_0/boost'
    - cd -
    - emcmake cmake -GNinja -Bbuild-web -DCMAKE_BUILD_TYPE=Release -DJNGL_VIDEO=0 -DBoost_INCLUDE_DIR=/tmp/boost_1_82_0
    - mv data/ build-web/
    - ninja -Cbuild-web jntetri
  artifacts:
    paths:
    - build-web/

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" web
    - docker push "$CI_REGISTRY_IMAGE${tag}"

pages:
  stage: deploy
  dependencies:
    - web
  script:
  - mv build-web public
  - mv web/index.html public/
  artifacts:
    paths:
    - public
  only:
  - master

variables:
  CLICOLOR_FORCE: "1"
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: noninteractive
