image: fedora:34

linux:
  stage: build
  script:
    - dnf install -y git gcc-c++ fontconfig-devel freetype-devel libvorbis-devel libepoxy-devel libwebp-devel boost-python3-devel python3-devel cmake ninja-build SDL2-devel openal-soft-devel
    - cmake -Bbuild -GNinja
    - ninja -C build

server:
  image: ubuntu:20.04
  stage: build
  script:
    - apt-get update && apt-get install -y cmake ninja-build libsoci-dev libsqlite3-dev g++ git libboost-system-dev libboost-coroutine-dev
    - cd server
    - cmake -Bbuild -GNinja
    - cmake --build build

web:
  image: emscripten/emsdk
  stage: build
  script:
    - apt-get update && apt-get install -y ninja-build libboost-dev
    - emcmake cmake -GNinja -Bbuild-web -DCMAKE_BUILD_TYPE=Release -DJNGL_VIDEO=0
    - mv data/ build-web/
    - ninja -Cbuild-web

pages:
  stage: deploy
  dependencies:
    - web
  script:
  - mv build-web public
  artifacts:
    paths:
    - public
  only:
  - master

variables:
  CLICOLOR_FORCE: "1"
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: noninteractive
